server:
  error:
    include-message: always
    include-binding-errors: always

  port: 8081
  #address: 192.168.132.96


spring:
  datasource:
    url: jdbc:mysql://scoutcompass-db.chg4ims6kcai.ap-south-1.rds.amazonaws.com:3306/scoutcompass-db-identifier
    username: admin
    password: scoutcompass1234
    driver-class-name: com.mysql.cj.jdbc.Driver

#    url: jdbc:mysql://localhost:3306/scout_compass_schema
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect:
        format_sql: true
    show-sql: true
  logging:
    file:
      name: ./apilogs/scout-compass-api.log

  servlet:
      multipart:
        enabled: true
        max-file-size: 10MB
        max-request-size: 10MB









